name: Lint and Standards
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Lint and check standards
    runs-on: ubuntu-latest
    defaults:
      cmd:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - name: Prettier
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: format

      - name: Lint
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: lint
